// frontend/src/components/ImageCard.jsx
import {useEffect, createRef} from 'react';
const MAX_WIDTH = 300;
const MAX_HEIGHT = 400;

export default function ImageCard(props) {
	const mediaRef = createRef();
	useEffect(() => {
		const media = mediaRef.current;
		const w = media.videoWidth || media.width;
		const h = media.videoHeight || media.height;
		if (w > h) {
			media.style.width = MAX_WIDTH + 'px';
			media.style.height = MAX_WIDTH * h / w + 'px';
		} else {
			media.style.width = MAX_HEIGHT * w / h + 'px';
			media.style.height = MAX_HEIGHT + 'px';
		}
	}, []);
	return (
		<div
			className='image-card cursor-pointer relative m-0.5 flex items-center justify-center'
			title={props.tags?.length ? props.tags.join(', ') : ''}
		>
			{props.type === 'image' ?
				<img src={props.url} alt={props.tags?.length ? props.tags.join(', ') : ''} className='block' ref={mediaRef} />
				: <video src={props.url} ref={mediaRef} autoPlay={true} loop></video>
			}
			<div className='image-card-tags opacity-0 absolute bottom-0 left-0 w-full box-border px-1 bg-black bg-opacity-50 text-white overflow-ellipsis overflow-hidden whitespace-nowrap'>
				{props.tags?.length ? props.tags.join(', ') : ''}
			</div>
		</div>
	);

}

// frontend/src/components/ImageCard.svelte
<script>
	import {PUBLIC_API_KEY} from '$env/static/public';
	import ImageTag from './ImageTag.svelte';

	export let url;
	export let id;
	export let tags;

	let scroller;
	const mouseIn = () => {
		if (scroller.scrollWidth === scroller.offsetWidth)
			return;
		scroller.style.marginLeft = - (scroller.scrollWidth - scroller.offsetWidth + 5) + 'px';
	}
	const mouseOut = () => {
		scroller.style.marginLeft = '';
	}
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<div class="image-card" id={id}>
	<div class="image-card-tools">
		<div></div>
		<div></div>
		<div></div>
	</div>
	<img src={`/api/images/poster/${id}`} alt={tags.join(', ')}>
	{#if tags.length}
		<div class="image-card-tags"  on:mouseenter={mouseIn} on:mouseleave={mouseOut}>
			<div class="backdrop"></div>
			<div class='scroller' bind:this={scroller}>
				{#each tags as tag}
					<ImageTag>{tag}</ImageTag>
				{/each}
			</div>
		</div>
	{/if}
</div>

<style>
	.image-card {
		cursor: pointer;
		position: relative;
		width: 300px;
		height: 300px;
		border-radius: 15px;
		overflow: hidden;
		box-shadow: 0px 10px 20px #00000064;
		border: 1px solid #6262628a;
		& img {
		width: 100%;
		height: 100%;
		object-fit: cover;
		}
	}
	.image-card-tags {
		position: absolute;
		bottom: 0;
		left: 0;
		width: 100%;
		transform: translateY(200%);
		transition: transform .3s ease;
		& .backdrop {
			position: absolute;
			bottom: 0;
			left: 0;
			height: 200%;
			width: 100%;
			background: linear-gradient(to top, #0004, transparent 60%);
		}
		& .scroller {
			padding: 5px;
			display: flex;
			justify-content: start;
			align-items: center;
			gap: 8px;
		}
		&:hover .scroller {
			transition: margin-left 3s linear;
		}
	}
	.image-card:hover {
		& .image-card-tags {
			transform: translateY(0);
		}
	}
</style>
