// frontend/src/components/ImageCard.svelte
<script>
	import {PUBLIC_API_KEY} from '$env/static/public';
	import ImageTag from './ImageTag.svelte';

	export let url;
	export let id;
	export let tags;

	let scroller;
	const mouseIn = () => {
		if (scroller.scrollWidth === scroller.offsetWidth)
			return;
		scroller.style.marginLeft = - (scroller.scrollWidth - scroller.offsetWidth + 5) + 'px';
	}
	const mouseOut = () => {
		scroller.style.marginLeft = '';
	}
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<div class="image-card" id={id}>
	<div class="image-card-tools">
		<div></div>
		<div></div>
		<div></div>
	</div>
	<img src={`/api/images/poster/${id}`} alt={tags.join(', ')}>
	{#if tags.length}
		<div class="image-card-tags"  on:mouseenter={mouseIn} on:mouseleave={mouseOut}>
			<div class="backdrop"></div>
			<div class='scroller' bind:this={scroller}>
				{#each tags as tag}
					<ImageTag>{tag}</ImageTag>
				{/each}
			</div>
		</div>
	{/if}
</div>

<style>
	.image-card {
		cursor: pointer;
		position: relative;
		width: 300px;
		height: 300px;
		border-radius: 15px;
		overflow: hidden;
		box-shadow: 0px 10px 20px #00000064;
		border: 1px solid #6262628a;
		& img {
		width: 100%;
		height: 100%;
		object-fit: cover;
		}
	}
	.image-card-tags {
		position: absolute;
		bottom: 0;
		left: 0;
		width: 100%;
		transform: translateY(200%);
		transition: transform .3s ease;
		& .backdrop {
			position: absolute;
			bottom: 0;
			left: 0;
			height: 200%;
			width: 100%;
			background: linear-gradient(to top, #0004, transparent 60%);
		}
		& .scroller {
			padding: 5px;
			display: flex;
			justify-content: start;
			align-items: center;
			gap: 8px;
		}
		&:hover .scroller {
			transition: margin-left 3s linear;
		}
	}
	.image-card:hover {
		& .image-card-tags {
			transform: translateY(0);
		}
	}
</style>

// frontend/src/components/ImageCard.tsx
import { createRef, MouseEventHandler, useEffect, useRef, useState } from 'react';
import { MdDownload, MdEdit, MdOpenInNew } from 'react-icons/md';

export default function ImageCard(props: ImageCardProps) {
	const mediaRef = useRef<HTMLImageElement>(null);
	const containerRef = useRef<HTMLDivElement>(null);
	const tagsRef = useRef<HTMLDivElement>(null);
	const [isLoaded, setLoaded] = useState(false);
	const [isDownloading, setDownloading] = useState(false);
	useEffect(() => {
		if (!containerRef.current)
			return;
		const observer = new IntersectionObserver(([entry]) => {
			if (entry.isIntersecting && !isLoaded)
				setLoaded(true);
		}, {
			root: null,
			threshold: 0.01
		});
		observer.observe(containerRef.current);
	}, [containerRef, isLoaded, props.id]);

	const download = () => {
		setDownloading(true);
		fetch(`${process.env.REACT_APP_API}/download/${props.id}`)
			.then(response => response.blob())
			.then(blob => {
				const blobURL = URL.createObjectURL(blob);
				const a = document.createElement('a');
				a.href = blobURL;
				a.style.display = 'none';
				a.download = props.id;
				document.body.appendChild(a);
				a.click();
				a.remove();
				setDownloading(false);
			}).catch(() => null);
	};

	const mouseIn: MouseEventHandler<HTMLDivElement> = e => {
		const elm = tagsRef.current!;
		const computed = - (elm.scrollWidth - elm.offsetWidth) + 'px';
		elm.style.marginLeft = computed;
	};

	const mouseLeave: MouseEventHandler<HTMLDivElement> = e => {
		const elm = tagsRef.current!;
		elm.style.marginLeft = '';
	}

	return (
		<div
			id={props.id}
			className='group image-card cursor-pointer relative m-1 flex items-center justify-center rounded-md bg-gray-700 overflow-hidden [width:300px] [height:300px]'
			title={props.tags.join(', ')}
			onClick={props.onClick}
			onMouseEnter={mouseIn}
			onMouseLeave={mouseLeave}
			ref={containerRef}
		>
			{isDownloading && <div className='loader absolute w-4 h-4 z-20'></div>}
			{
				isLoaded ?
					<img
						src={`${process.env.REACT_APP_API}/posters/${props.id}?authorization=${process.env.REACT_APP_API_KEY}`}
						alt={props.tags.join(', ')}
						className='block w-full h-full object-cover z-10'
						width={300}
						height={300}
						ref={mediaRef}
					/>
					: null

			}
			<div className='image-card-actions w-full absolute z-20 top-0 left-0 flex justify-end p-1 flex-row opacity-0 transition-opacity duration-100'>
				<div className='image-card-actions-background absolute top-0 left-0 w-full h-[150%]'></div>
				<MdEdit color='#fff' size={24} onClick={e => { e.stopPropagation(); props.edit(); }} title={'Edit'} className='transform hover:translate-y-1 transition-all duration-100'></MdEdit>
				<a href={props.url} target='_blank' rel='noreferrer' onClick={e => e.stopPropagation()}>
					<MdOpenInNew color='#fff' size={24} title='Download' className='transform hover:translate-y-1 transition-all duration-100'></MdOpenInNew>
				</a>
				<MdDownload color='#fff' size={24} title='Download' className='transform hover:translate-y-1 transition-all duration-100' onClick={e => { e.stopPropagation(); download(); }}></MdDownload>
			</div>
			<div className='image-card-tags p-1 opacity-0 absolute bottom-0 overflow-visible left-0 w-full box-border px-1 text-white z-20'>
				<div className='image-card-tags-background absolute bottom-0 left-0 w-full h-[250%]'></div>
					<div className='overflow-x-visible h-7 relative w-auto whitespace-nowrap group-hover:duration-[4s] group-hover:transition-all group-hover:ease-linear' ref={tagsRef}>
					{
						props.tags.map(p =>
							<div key={p} className='inline-block mx-1 px-2 py-px bg-white/20 rounded-full border-[1px] border-white/50 z-50'>
								{p}
							</div>
						)
					}
				</div>
			</div>
		</div >
	);
}

export interface ImageCardProps {
	id: string;
	tags: string[];
	onClick: MouseEventHandler;
	edit: () => void;
	url: string;
}
